# Dependencies
highlighter:   rouge   #pygments

gems: 
  - jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            Gagliano Taliun Lab
tagline:          'in Montreal, Canada'
description:      'in computational genetics'
url:              https://sgagliano.github.io
baseurl:          /

author:
  name:           ''
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sgagliano/sgagliano.github.io
