# Dependencies
highlighter:   rouge   #pygments

gems: 
  - jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            Sarah Gagliano Taliun
tagline:          'PhD'
description:      'Post Poctoral Research Fellow,  University of Michigan'
url:              https://sgagliano.github.io
baseurl:          /

author:
  name:           'Yanxiao Zhang'
  url:            https://twitter.com/zhangyx.shawn

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sgagliano/shawnzhangyx.github.io
